services:
 postgres:
  container_name: OrganizationService
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: organization_service_db
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
  - 5438:5432
  volumes:
  - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: