services:
 postgres:
  container_name: OrganizationService
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: organization_service_db
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
  - 5438:5432
  volumes:
  - postgres-data:/var/lib/postgresql/data
 seq:
   image: datalust/seq:latest
   container_name: OrganizationServiceSeq
   restart: always
   environment:
    - ACCEPT_EULA=Y
    - SEQ_FIRSTRUN_NOAUTHENTICATION=true
   ports:
    - 5342:5341
    - 8082:80
  


volumes:
  postgres-data: